/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sparky.firstswingproject;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Vector;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.HTMLDocument.Iterator;

import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author SparkySmith
 */
public class FirstWindow extends javax.swing.JFrame {
//	Creating the vector list to store anytype and anynumber of data
	Vector taskData = new Vector();
	int count=0;
//	------------------
//	Creating excel sheet
	XSSFWorkbook workbook = new XSSFWorkbook();
    XSSFSheet sheet = workbook.createSheet("Task Data");
    
//    .....................................
    /**
     * Creates new form FirstWindow
     */
    public FirstWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        entry_panel = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        view_btn = new javax.swing.JButton();
        date_lbl = new javax.swing.JLabel();
        date_txt = new javax.swing.JTextField();
        task_lbl = new javax.swing.JLabel();
        task_txt = new javax.swing.JTextField();
        task_type_lbl = new javax.swing.JLabel();
        task_drop = new javax.swing.JComboBox<>();
        target_lbl = new javax.swing.JLabel();
        date_txt1 = new javax.swing.JTextField();
        submit_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        task_panel = new javax.swing.JPanel();
        tasks_txt = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        taskTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_bg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new java.awt.CardLayout());

        entry_panel.setBackground(new java.awt.Color(204, 255, 255));

        heading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        heading.setText("Todo App");

        view_btn.setBackground(new java.awt.Color(204, 204, 204));
        view_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        view_btn.setText("View");
        view_btn.setActionCommand("view");
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					view_btnActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        date_lbl.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        date_lbl.setText("Date");

        date_txt.setBackground(new java.awt.Color(204, 204, 255));

        task_lbl.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        task_lbl.setText("Task");

        task_txt.setBackground(new java.awt.Color(204, 204, 255));

        task_type_lbl.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        task_type_lbl.setText("Task Type");

        task_drop.setBackground(new java.awt.Color(204, 204, 255));
        task_drop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "C++", "Python", "DSA", "Maths", "Conduira", "Others" }));
        task_drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_dropActionPerformed(evt);
            }
        });

        target_lbl.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        target_lbl.setText("Target Date");

        date_txt1.setBackground(new java.awt.Color(204, 204, 255));

        submit_btn.setBackground(new java.awt.Color(204, 204, 204));
        submit_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					submit_btnActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jLabel1.setText("(22 Aug 2002)");

        jLabel2.setText("(22 Aug 2002)");

        javax.swing.GroupLayout entry_panelLayout = new javax.swing.GroupLayout(entry_panel);
        entry_panel.setLayout(entry_panelLayout);
        entry_panelLayout.setHorizontalGroup(
            entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entry_panelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entry_panelLayout.createSequentialGroup()
                        .addGroup(entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(task_type_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(date_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(task_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(target_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(entry_panelLayout.createSequentialGroup()
                                .addComponent(date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addComponent(task_drop, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(entry_panelLayout.createSequentialGroup()
                                .addComponent(date_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(task_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entry_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(heading)
                        .addGap(235, 235, 235)
                        .addComponent(view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(entry_panelLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(submit_btn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        entry_panelLayout.setVerticalGroup(
            entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entry_panelLayout.createSequentialGroup()
                .addGroup(entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entry_panelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(entry_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_lbl)
                    .addComponent(date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task_drop, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(task_type_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(task_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(target_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(submit_btn)
                .addGap(53, 53, 53))
        );

        jPanel1.add(entry_panel, "card2");

        task_panel.setBackground(new java.awt.Color(204, 255, 255));

        tasks_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tasks_txt.setText("Tasks");

        back_btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back_btn.setText("<--");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Task type", "Task Name", "Target Date"
            }
        ));
        taskTable.setViewportView(jTable1);

        javax.swing.GroupLayout task_panelLayout = new javax.swing.GroupLayout(task_panel);
        task_panel.setLayout(task_panelLayout);
        task_panelLayout.setHorizontalGroup(
            task_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task_panelLayout.createSequentialGroup()
                .addGroup(task_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(task_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn)
                        .addGap(249, 249, 249)
                        .addComponent(tasks_txt))
                    .addGroup(task_panelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(taskTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        task_panelLayout.setVerticalGroup(
            task_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task_panelLayout.createSequentialGroup()
                .addGroup(task_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(task_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn))
                    .addGroup(task_panelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(tasks_txt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(taskTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(task_panel, "card3");

        javax.swing.GroupLayout panel_bgLayout = new javax.swing.GroupLayout(panel_bg);
        panel_bg.setLayout(panel_bgLayout);
        panel_bgLayout.setHorizontalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_bgLayout.setVerticalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
	private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) throws IOException   {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
    
//    	Txtfield validitions
    	String date = date_txt.getText();
        String task_type =  (String)task_drop.getSelectedItem();
        String task_name = task_txt.getText();
        String target_date = date_txt1.getText();
        
    	if(date.isEmpty() || task_name.isEmpty() || target_date.isEmpty() ) {
            JOptionPane.showMessageDialog(this,"No Fields can be empty!");
    		
    	}else {
//    		count the num of submitions
    		count++;
//    	showing message when one task is submitted
        JOptionPane.showMessageDialog(this,"One Task Created!");
//       Getting the data from the txtfields
        
        
        
//       Adding txtfield data to the vector list
        String data_arr[] = {date, task_name, target_date, task_type};
        taskData.addElement(data_arr);
        
        
//       Resetting the textfields
        date_txt.setText("");
        date_txt1.setText("");
        task_txt.setText("");
        
//      Working with excel sheet
        
        int rows = taskData.size();
        int cols = ((String[])taskData.elementAt(0)).length;
        
        System.out.println(rows);
        System.out.println(cols);
        
        for(int r=0;r<rows;r++) {
        	XSSFRow row  = sheet.createRow(r);
        	for(int c=0;c<cols;c++) {
        		XSSFCell cell = row.createCell(c);
        		String val = ((String[])taskData.elementAt(r))[c];
        		cell.setCellValue((String)val);
        		
        		
        	}
        }
        
        FileOutputStream outstream = new FileOutputStream(new File(".\\dataFiles\\tasks.xlsx"));
        try {
			workbook.write(outstream);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        outstream.close();
        System.out.println("Excel sheet created!");
        
  
    	}
    }//GEN-LAST:event_submit_btnActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_view_btnActionPerformed
        // TODO add your handling code here:
        task_panel.show();
        entry_panel.hide();
      
        if(count!=0) {
        String filepath = ".\\dataFiles\\tasks.xlsx";
        
        FileInputStream inputstream = new FileInputStream(filepath);
        
        workbook= new XSSFWorkbook(inputstream);
        sheet = workbook.getSheetAt(0);
//        Using for loop
        int rows = sheet.getLastRowNum()+1;
        int cols = sheet.getRow(0).getLastCellNum();
        String taskData[][] = new String[rows][cols];
//        Creating the defaultmodel of the jtabl
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.setRowCount(0);
//        read from excel and make an array and put that in table
        System.out.println(rows);
        for(int r=0;r<rows;r++) {
        	XSSFRow row = sheet.getRow(r);
        	for(int c=0;c<cols;c++) {
        		XSSFCell cell = row.getCell(c);
//        		switch(cell.getCellType()) {
//        		case STRING:
//        			taskData[r][c] = cell.getStringCellValue();
//        			break;
//        		case NUMERIC:
//        			taskData[r][c] = cell.getNumericCellValue();
//        			break;
//        		case BOOLEAN:
//        			taskData[r][c] = cell.getBooleanCellValue();
//        			break;
//        		}
        		taskData[r][c] = cell.getStringCellValue();
        		System.out.println(r+" "+c);
        		System.out.println(cell.getStringCellValue());
        		
        	}
        	tblModel.addRow(taskData[r]);
        }
        
//        inputstream.close();
        
        }
    }//GEN-LAST:event_view_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        entry_panel.show();
        task_panel.hide();
    }//GEN-LAST:event_back_btnActionPerformed

    private void task_dropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_dropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task_dropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel date_lbl;
    private javax.swing.JTextField date_txt;
    private javax.swing.JTextField date_txt1;
    private javax.swing.JPanel entry_panel;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel_bg;
    private javax.swing.JButton submit_btn;
    private javax.swing.JLabel target_lbl;
    private javax.swing.JScrollPane taskTable;
    private javax.swing.JComboBox<String> task_drop;
    private javax.swing.JLabel task_lbl;
    private javax.swing.JPanel task_panel;
    private javax.swing.JTextField task_txt;
    private javax.swing.JLabel task_type_lbl;
    private javax.swing.JLabel tasks_txt;
    private javax.swing.JButton view_btn;
    // End of variables declaration//GEN-END:variables
}
